name: trujillo_mobility
description: "Trujillo Mobility - Public transport app for Trujillo, Peru"
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core dependencies
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  go_router: ^17.0.0
  latlong2: ^0.9.1
  maplibre_gl: ^0.24.1
  equatable: ^2.0.7

  # Trufi Core packages from git
  trufi_core_interfaces:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_interfaces

  trufi_core_ui:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_ui

  trufi_core_utils:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_utils

  trufi_core_maps:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_maps

  trufi_core_navigation:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_navigation

  trufi_core_routing:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_routing

  trufi_core_routing_ui:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_routing_ui

  trufi_core_search_locations:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_search_locations

  trufi_core_poi_layers:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_poi_layers

  trufi_core_base_widgets:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_base_widgets

  trufi_core_custom_material:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_custom_material

  # Screen packages
  trufi_core_home_screen:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_home_screen

  trufi_core_saved_places:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_saved_places

  trufi_core_transport_list:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_transport_list

  trufi_core_fares:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_fares

  trufi_core_feedback:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_feedback

  trufi_core_settings:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_settings

  trufi_core_about:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_about

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  trufi_core_interfaces:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_interfaces

  trufi_core_ui:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_ui

  trufi_core_utils:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_utils

  trufi_core_maps:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_maps

  trufi_core_navigation:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_navigation

  trufi_core_routing:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_routing

  trufi_core_routing_ui:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_routing_ui

  trufi_core_search_locations:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_search_locations

  trufi_core_poi_layers:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_poi_layers

  trufi_core_base_widgets:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_base_widgets

  trufi_core_custom_material:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/trufi_core_custom_material

  trufi_core_home_screen:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_home_screen

  trufi_core_saved_places:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_saved_places

  trufi_core_transport_list:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_transport_list

  trufi_core_fares:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_fares

  trufi_core_feedback:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_feedback

  trufi_core_settings:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_settings

  trufi_core_about:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: v5.0.0
      path: packages/screens/trufi_core_about

flutter:
  uses-material-design: true

  assets:
    - assets/images/
